services:

  app:
    build: .
    container_name: parcel-tracker-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_DB_HOST: mongo
      MONGO_DB_PORT: 27017
      MONGO_DB_USER: root
      MONGO_DB_PASSWORD: root

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
