spring:
  application:
    name: parcel-delivery
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USER:root}:${MONGO_PASSWORD:root}@${MONGO_DB_HOST:localhost}:${MONGO_DB_PORT:27017}/parcel-delivery
